# Site settings
title: Yao-Min Huang
email: yaomin.huang@gmail.com 
description: "Yao-Min Huang's blog."
timezone: Aisa/Taipei
baseurl: ""
url: "http://ymhuang.github.io"
github_username:  ymhuang

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-midnight